name: Auto-Merge Dependabot

on:
  workflow_run:
    types:
      - completed
    workflows:
      - 'Integrate'

jobs:
  mention-to-teams:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: auto-merge
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PRESET: DEPENDABOT_MINOR
